server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      # consul注册中心地址
      host: 192.168.16.124
      port: 8500
      discovery:
        hostname: 192.168.16.124
        service-name: ${spring.application.name}
        prefer-ip-address: true
        ip-address: 192.168.16.124
